name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Or your desired Node.js version
      - name: Install dependencies
        run: npm install
      - name: Build and export Next.js app
        run: npm run build && npm run export # Assuming you have 'export' script in package.json
      - name: Add .nojekyll file
        run: touch out/.nojekyll # Assuming 'out' is your export directory
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Assuming 'out' is your export directory
